
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (1,11831622466, 'Selle', 'Sore', '33 Straubel Center', 'ssore1@gmpg.org', '$2a$10$vYxq4JAQ2YTpleuCoYRtvOP8bcfS9gfgmbJU7L/MRcIGbWmSGtZfS', 'Hyundai', 'FkS-6528', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (2,46995592415, 'Jessamyn', 'Kew', '5694 Boyd Parkway', 'jkew2@hc360.com', '$2a$10$YxemIeuJq4wB.LMMqHmR8e8JrGQO5fGs2IwmmWj1rtSFf9swH1Usu', 'Toyota', 'rZk-4114', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (3,52901060424, 'Leshia', 'Rutgers', '7691 American Park', 'lrutgers3@ustream.tv', '$2a$10$FKg42N1H9SytX7kr6m7TGu8T4uOcAdF5DTZOrI69CxPMVuVMm9iiy', 'Porsche', 'tTo-5273', 'Admin');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (4,28096176806, 'Johnna', 'Raw', '7 Continental Road', 'jraw4@auda.org.au', 'k6vKbQxZ9hmC', 'Pontiac', 'ykU-7218', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (5,52332286169, 'Karrie', 'Bowne', '26968 Dovetail Crossing', 'kbowne5@ameblo.jp', 'LXZcPT9xpuia', 'GMC', 'kLi-7062', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (6,99318629386, 'Sherwynd', 'Stiff', '164 Prentice Pass', 'sstiff6@wikimedia.org', 'qW2yaFD4rxj', 'BMW', 'CLu-7393', 'Admin');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (7,57766805186, 'Mel', 'Gilardone', '38 Northridge Street', 'mgilardone7@un.org', '3hzMcV0dxf', 'Mitsubishi', 'Jrp-3260', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (8,18735543926, 'Malorie', 'Padgham', '194 Rockefeller Hill', 'mpadgham8@dagondesign.com', '9NGsyOs', 'Mitsubishi', 'tNw-4476', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (9,82308623039, 'Ariella', 'Gendrich', '75 Coleman Point', 'agendrich9@engadget.com', 'GI0Jr5v', 'Suzuki', 'bMS-6227', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (10,91137728996, 'Coop', 'Trundell', '5 Twin Pines Trail', 'ctrundella@typepad.com', 'ZMcYlnrqR5Q', 'Suzuki', 'xbH-6792', 'Admin');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (11,41793186154, 'Otis', 'Bendare', '30 Magdeline Place', 'obendareb@geocities.com', 'TQBDLm', 'BMW', 'oMp-4959', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (12,57979758611, 'Terrel', 'Bosley', '2 Pawling Avenue', 'tbosleyc@joomla.org', 'kaBboP', 'Chevrolet', 'inD-9968', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (13,13259588814, 'Martguerita', 'Crammy', '2298 Everett Park', 'mcrammyd@odnoklassniki.ru', '8Uea0lpAZ6D', 'Ford', 'deG-1004', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (14,60044810425, 'Willie', 'Lamperd', '306 Dorton Drive', 'wlamperde@google.com', 'edOJvAnx6', 'Isuzu', 'TrS-0105', 'Admin');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (15,85794055327, 'Yard', 'O''Meara', '76375 Jenna Court', 'yomearaf@cocolog-nifty.com', 'OrXzsP', 'GMC', 'MPu-8107', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (16,92533517970, 'Ariel', 'Nijssen', '7198 Pine View Circle', 'anijsseng@github.com', '2S6vpquufs9', 'Isuzu', 'SZz-0594', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (17,71782761029, 'Bendick', 'Mongenot', '6103 John Wall Pass', 'bmongenoth@bbb.org', 'MAnnAjqFqOl', 'Cadillac', 'AiY-9792', 'User');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (18,61484782039, 'Ignaz', 'Paskell', '55575 Cordelia Point', 'ipaskelli@shop-pro.jp', 'tN0Gl8Yczt', 'Ford', 'Kyp-8299', 'Admin');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (19,18242514994, 'Mord', 'Beinisch', '786 Carpenter Parkway', 'mbeinischj@prweb.com', 'vCen8fVNL6DZ', 'Lincoln', 'YwW-0068', 'Admin');
insert into owneruser (id,afm, onoma, epitheto, dieuthinsi, email, kwdikoxristi, markaoximatos, pinakidaoximatos, tipoxristi) values (20,29712431337, 'Jarvis', 'Scranney', '2 Cambridge Point', 'jscranney0@google.pl', 'fqTvlOr', 'Audi', 'IlZ-5733', 'Admin');




insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (1, '2017-08-08', 'finished', 'car brakes', 23.788, 'the_owner', 'medium',1);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (2, '2018-05-11', 'finished', 'car brakes', 58.062, 'the_owner', 'large',2);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (3, '2018-12-17', 'waiting for spare parts', 'engine', 1978.57, 'the_owner', 'small',3);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (4, '2017-03-27', 'almost Finished', 'oil change', 963.13, 'the_owner', 'large',4);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (5, '2018-04-22', 'finished', 'engine', 670.68, 'the_owner', 'small',5);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (6, '2017-11-22', 'waiting for spare parts', 'oil change', 175, 'the_owner', 'large',6);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (7, '2018-04-14', 'waiting for spare parts', 'engine', 116.350, 'the_owner', 'large',7);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (8, '2017-06-15', 'waiting for spare parts', 'engine', 73.60, 'the_owner', 'large',8);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (9, '2018-01-16', 'waiting for spare parts', 'oil change', 28.296, 'the_owner', 'small',9);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (10, '2018-01-12', 'waiting for spare parts', '', 87.858, 'the_owner', 'medium',10);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (11, '2018-04-03', 'finished', 'engine', 129.493, 'the_owner', 'large',11);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (12, '2017-08-01', 'almost Finished', 'tires', 49.73, 'the_owner', 'small',12);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (13, '2017-09-21', 'finished', 'tires', 1.1199, 'the_owner', 'medium',13);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (14, '2017-07-23', 'almost Finished', 'oil change', 1227.26, 'the_owner', 'medium',14);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (15, '2016-10-30', 'waiting for spare parts', '', 143.656, 'the_owner', 'medium',15);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (16, '2017-11-06', 'almost Finished', 'engine', 16463, 'the_owner', 'small',16);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (17, '2017-11-06', 'waiting for spare parts', 'oil change', 767.2, 'the_owner', 'large',17);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (18, '2018-07-06', 'almost Finished', 'tires', 12.3732, 'the_owner', 'small',18);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (19, '2018-03-01', 'waiting for spare parts', 'oil change', 13758.4, 'the_owner', 'small',19);
insert into repair (id, datetime, katastasi, eidosepiskeuis, kostos, owner, perigrafi,userOwner_id) values (20, '2018-12-17', 'almost Finished', 'car brakes', 63.322, 'the_owner', 'large',0);
